version: '3'

services:
  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./web/out:/var/www/out
    ports:
      - 80:80
    # environment:
    #   - SSL_CERT=***TBC***
    #   - SSL_KEY=***TBC***