version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./web:/public
    ports:
      - 80:80
    # environment:
    #   - SSL_CERT=***TBC***
    #   - SSL_KEY=***TBC***